local key = vim.keymap

key.set("n", "<c-k>", ":wincmd k<CR>")
key.set("n", "<c-j>", ":wincmd j<CR>")
key.set("n", "<c-h>", ":wincmd h<CR>")
key.set("n", "<c-l>", ":wincmd l<CR>")
key.set("n", "<c-d>", "<C-d>zz")
key.set("n", "<c-u>", "<C-u>zz")
key.set("n", "<Esc>", "<cmd>nohlsearch<CR>")
key.set("n", "<leader>x", "<cmd>source %<CR>")
key.set("n", "<leader>pe", ":Copilot enable<CR>", { desc = "Enable Copilot" })
key.set("n", "<leader>pd", ":Copilot disable<CR>", { desc = "Disable Copilot" })

key.set("n", "K", vim.lsp.buf.hover, { desc = "Show hover" })
key.set("n", "<leader>gd", vim.lsp.buf.definition, { desc = "Go to definition" })
key.set("n", "<leader>gr", vim.lsp.buf.references, { desc = "Go to references" })
key.set({ "n", "v" }, "<leader>ca", vim.lsp.buf.code_action, { desc = "Code action" })
key.set("n", "<leader>rn", vim.lsp.buf.rename, { desc = "Rename" })
key.set("n", "<leader>e", vim.diagnostic.open_float, { desc = "Show diagnostics" })
key.set("n", "<leader>en", vim.diagnostic.goto_next, { desc = "Go to next diagnostic" })
key.set("n", "<leader>ep", vim.diagnostic.goto_prev, { desc = "Go to previous diagnostic" })

key.set("n", "<leader>mp", ":MarkdownPreviewToggle<CR>", { desc = "Toggle markdown preview" })

key.set("n", "<leader>cf", vim.lsp.buf.format, { desc = "Format" })

key.set("n", "<leader>zf", "<cmd>Telekasten find_notes<CR>", { desc = "Find notes" })
key.set("n", "<leader>zt", "<cmd>Telekasten show_tags<CR>", { desc = "Show tags" })
key.set("n", "<leader>zn", "<cmd>Telekasten new_note<CR>", { desc = "New note" })

key.set("n", "<leader>ut", ":UndotreeToggle<CR>", { desc = "Toggle undotree" })

local harpoon = require("harpoon")
harpoon.setup()

vim.keymap.set("n", "<leader>a", function()
	harpoon:list():add()
end, { desc = "Harpoon add project" })
vim.keymap.set("n", "<leader>h", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = "Harpoon toggle quick menu" })
vim.keymap.set("n", "<C-q>", function()
	harpoon:list():select(1)
end, { desc = "Harpoon select [1] project" })
vim.keymap.set("n", "<C-w>", function()
	harpoon:list():select(2)
end, { desc = "Harpoon select [2] project" })
vim.keymap.set("n", "<C-e>", function()
	harpoon:list():select(3)
end, { desc = "Harpoon select [3] project" })
vim.keymap.set("n", "<C-r>", function()
	harpoon:list():select(4)
end, { desc = "Harpoon select [4] project" })
-- vim.keymap.set("n", "<C-S-.>", function() harpoon:list():prev() end)
-- vim.keymap.set("n", "<C-S-.>", function() harpoon:list():next() end)

key.set("n", "<leader>tp", ":TypstPreviewToggle<CR>", { desc = "Toggle typst preview" })

key.set("n", "-", "<CMD>Oil<CR>", { desc = "Open parent directory" })
key.set("n", "<space>-", require("oil").toggle_float, { desc = "Toggle oil float" })
